// <auto-generated />
using System;
using BiddingSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiddingSystem.Migrations
{
    [DbContext(typeof(BiddingSystemContext))]
    [Migration("20240125184910_AddedAuctionToUser")]
    partial class AddedAuctionToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiddingSystem.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndOfAuction")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<double>("MinimumBidIncrement")
                        .HasColumnType("float");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<double>("StartingPrice")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WinningBidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("BiddingSystem.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("BiddingSystem.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvailableForAuction")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            AvailableForAuction = true,
                            Name = "Napoleon's Favorite Hat",
                            UserId = 1000
                        },
                        new
                        {
                            Id = 1001,
                            AvailableForAuction = true,
                            Name = "McDonald's Forever Free Nuggets",
                            UserId = 1000
                        },
                        new
                        {
                            Id = 1002,
                            AvailableForAuction = true,
                            Name = "Eiffel Tower Top Light",
                            UserId = 1002
                        });
                });

            modelBuilder.Entity("BiddingSystem.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BiddingSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Credit")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FrozenCredit")
                        .HasColumnType("float");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Credit = 10000.0,
                            Email = "seller1@gmail.com",
                            FrozenCredit = 0.0,
                            PasswordHash = "$2a$11$LdtBjpQFPjfcv43wuKKu1Ossj7xlIt8CIc7SCOOwPQd2EMGcHTF6S",
                            Username = "Seller 1"
                        },
                        new
                        {
                            Id = 1001,
                            Credit = 10000.0,
                            Email = "buyer1@gmail.com",
                            FrozenCredit = 0.0,
                            PasswordHash = "$2a$11$gwoVj7C2vGBwPPpQSoKU2OBtvQU/SbTtY9r39HmbDiwbqZtFy/JJ2",
                            Username = "Buyer 1"
                        },
                        new
                        {
                            Id = 1002,
                            Credit = 10000.0,
                            Email = "buyer2@gmail.com",
                            FrozenCredit = 0.0,
                            PasswordHash = "$2a$11$ApwUYTwoXNIKqCqNgwZI3.LfRxLLF0Ssse9PwxQh9xVbMBSKB7v92",
                            Username = "Buyer 2"
                        },
                        new
                        {
                            Id = 1003,
                            Credit = 0.0,
                            Email = "buyer3@gmail.com",
                            FrozenCredit = 0.0,
                            PasswordHash = "$2a$11$.FRwCx7KzLiGpSyyRVFg7eYqZa.3z7wyCfLf7.fDwzg6GSmqL70KO",
                            Username = "Buyer 3"
                        },
                        new
                        {
                            Id = 1004,
                            Credit = 0.0,
                            Email = "owner@gmail.com",
                            FrozenCredit = 0.0,
                            PasswordHash = "$2a$11$PjZDhP3OHQ6XhCcIMB8eT.3S8UA9j0WTuvHB3loUKOYKwC1Y.UpNq",
                            Username = "Owner"
                        });
                });

            modelBuilder.Entity("BiddingSystem.Models.Auction", b =>
                {
                    b.HasOne("BiddingSystem.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiddingSystem.Models.User", null)
                        .WithMany("Auctions")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BiddingSystem.Models.Bid", b =>
                {
                    b.HasOne("BiddingSystem.Models.Auction", null)
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiddingSystem.Models.User", null)
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiddingSystem.Models.Item", b =>
                {
                    b.HasOne("BiddingSystem.Models.User", null)
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiddingSystem.Models.Notification", b =>
                {
                    b.HasOne("BiddingSystem.Models.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiddingSystem.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("BiddingSystem.Models.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");

                    b.Navigation("Items");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
